name: HarperDB Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Start HarperDB container
      run: |
        docker-compose -f docker/docker-compose.yml up -d
        sleep 10  # Wait for container to start
        
    - name: Run workflow
      run: |
        python scripts/workflow.py
        
    - name: Upload metrics
      uses: actions/upload-artifact@v3
      with:
        name: workflow-metrics
        path: metrics/workflow_metrics.json
        
    - name: Cleanup
      run: |
        docker-compose -f docker/docker-compose.yml down 